# Generated by Django 4.0.3 on 2022-03-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numOfpages', models.BigIntegerField()),
                ('author', models.CharField(max_length=50)),
                ('typeOfbook', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
